import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StateCompo } from './context/StateCompo.jsx'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Very - Copy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StateCompo>
    <html lang="en">
      <link rel="icon" type="image/svg+xml" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFwAAABcCAMAAADUMSJqAAAAclBMVEX3nSQAAAEAAAD3nyb8oCW4dBv/oiX3oSj/pCa7dxvVhx/tliLjkCHlkiHPgx6vbxnEfRxaOQ11ShGGVROqbBljPw6TXRWMWRQ+JwkTCwJ6ThKYYRZHLQoJBQGgZhdNMQttRQ8vHgcjFgUoGgU2IggbEQSwCFoCAAACdklEQVRoge2Ya2OqMAyGWay1CHIRcHjbzs7m//+LQ2FT0rdQuXxan8/JS9K0aYrnORwOh8PxJxAcSzMrp8j3/WWD7yfReuNJ3VZEyw7iCKuLnBj78pBooQifm7U4SkPoJ3p55GZ8WnNrkbbNWi6lYVk8sSbNrZKPZb/Zr7VhVSrUFngR+cxBIrPadmtYlCvBGaoHLPTQEDqdA6xbx/SGvGirWIaZQTzvCLziBENf85WEodO7ccHrjBPkRikLHWbYVc0m438wpoS7fehmdOheFFOxtISrk6TZ7Luq2WR8hKHHTF2V3KyvmrXbfxT6J88wYhnSp4JyPW61746fU1YcvSwQeACJQuYctDLs24Z3Nxg63wutXQuOgin0HNaUu8tr7/3RTiyq2fCOQi95xeSmaJp4Gtpr46aq9d5KPljusiwPleWa3FAHJH4Bp0RIpeyjrgn2SP3VZiv3A2tKtHkmfTMCntOui+YJpN6ZbJqqJeLLprEPFccthl/WA5Ho2qCvSbQ9scHdcZqFUTur7jgUWNPWwDb8Q3A7vlB23+wyGh65gt2xGmRvAQsZHD6GnypDd6Q08pQS4fE86lAZ5jaisihOVR8vxrUDNJk2kzuNbWT4xvv5xNgWzF8bj9qXcdKmybQWz0cfJ1kYxOk0Vtr8jCDLEasndHRZV+Ijt2FDcJmxgSn4jMimab2e1EMnmkYaPyNsJn07JH+Qm1/hz8O3o/3AbIOMH9WJ3iaqZqN+vKvT4100mTrV0vQ6sfb1umwm/fSJR4Q1QoRJHieh6S/WeP25lB0Oh8OOxXzKFbMJz6K9+GU+5Sm1Fy1Wq9VU2prwVNJIuKX8DfU/GhOA9HaNAAAAAElFTkSuQmCC" />
      <body className={inter.className}>{children}
      </body>
    </html>
    </StateCompo>
  );
}
